stages:
  - parallel_execution

# Mirror job now in the same stage as deploy
sync_to_github:
  stage: parallel_execution
  script:
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/skynet-xy/post2video-processor.git
    - git fetch --all
    - git branch -a
    - |
      for branch in $(git branch -r | grep 'origin/' | grep -v '\->'); do
        branch_name=$(echo $branch | sed 's/origin\///');
        git push --force github $branch:refs/heads/$branch_name;
      done
    - git push --force --tags github
  only:
    - branches
    - tags

# Deploy job now in the same stage
deploy:
  stage: parallel_execution
  variables:
    PROJECT_PATH: /home/ducan/srv/post2video-processor
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - |
      ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
        cd $PROJECT_PATH &&
        git fetch --all &&
        git checkout $CI_COMMIT_REF_NAME &&
        git pull origin $CI_COMMIT_REF_NAME &&
        bash deploy.sh
      "
  only:
    - main
    - release