services:
  app:
    build: .
    container_name: reddit-comment-overlay-service
    ports:
      - "8000:8000"
    volumes:
      - ./download:/app/download
      - ./generated:/app/generated
      - ./assets:/app/assets
      - ./app:/app/app
      - ./keys:/app/keys
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
